[package]
name = "ec_forms"
version = "0.1.0"
authors = ["Bogdan Potishuk <bogdan@atollholding.com.ua>"]
edition = "2018"

[dependencies]
notify = "4.0.6"
log = "0.4.6"
log4rs = "0.8.1"
openssl-probe = "0.1.2"
openssl = { version = "0.10.15", feature = ["vendored"] }
base64 = "0.10.0"
