[package]
name = "cms-decrypt-srv"
version = "0.2.0"
authors = ["Bohdan Potishuk <dragon@noctilucence.io>"]
edition = "2021"

[dependencies]
notify = "4.0.17"
log = "0.4.17"
log4rs = "1.1.1"
openssl-probe = "0.1.5"
openssl = { version = "0.10.40", feature = ["vendored"] }
base64 = "0.13.0"
